# Base URL and Tokens
@baseUrl = http://127.0.0.1:8000/api
@tokenJohn = Token 67ac43d4f67589b659da387db848ffa6e554601a
@tokenNana = Token 131d4e6a80876c029387bd611dab098721a40266
@tokenBeto = Token 4a05e93a2a05af486ead148c1671a714e242e02e

# =======================================
# AUTHOR ACTIONS (John)
# =======================================

### CREATE SOCIAL_POST
POST {{baseUrl}}/social-posts/
Authorization: {{tokenJohn}}
Content-Type: application/json

{
    "title": "Meu Primeiro Post",
    "content": "Este é o conteúdo do post."
}

### GET SOCIAL_POST
GET {{baseUrl}}/social-posts/1/
Authorization: {{tokenJohn}}
Content-Type: application/json

### GET ALL SOCIAL_POST
GET {{baseUrl}}/social-posts/
Authorization: {{tokenJohn}}
Content-Type: application/json

### EDIT SOCIAL_POST
PATCH {{baseUrl}}/social-posts/1/
Authorization: {{tokenJohn}}
Content-Type: application/json

{
    "title": "Título Atualizado teste",
    "content": "Conteúdo atualizado do post."
}

### DELETE SOCIAL_POST
DELETE {{baseUrl}}/social-posts/1/
Authorization: {{tokenJohn}}

### COMMENT SOCIAL_POST
POST {{baseUrl}}/social-posts/1/comment/
Authorization: {{tokenJohn}}
Content-Type: application/json

{
    "content": "Obrigado Nana"
}

# =======================================
# USER ACTIONS (Nana)
# =======================================

### CREATE SOCIAL_POST
POST {{baseUrl}}/social-posts/
Authorization: {{tokenNana}}
Content-Type: application/json

{
    "title": "Meu Primeiro Post",
    "content": "Este é o conteúdo do post."
}

### GET SOCIAL_POST
GET {{baseUrl}}/social-posts/1/
Authorization: {{tokenNana}}
Content-Type: application/json

### GET ALL SOCIAL_POST
GET {{baseUrl}}/social-posts/
Authorization: {{tokenNana}}
Content-Type: application/json

### EDIT SOCIAL_POST
PATCH {{baseUrl}}/social-posts/1/
Authorization: {{tokenNana}}
Content-Type: application/json

{
    "title": "Título Atualizado teste",
    "content": "Conteúdo atualizado do post."
}

### DELETE SOCIAL_POST
DELETE {{baseUrl}}/social-posts/1/
Authorization: {{tokenNana}}

### COMMENT SOCIAL_POST
POST {{baseUrl}}/social-posts/1/comment/
Authorization: {{tokenNana}}
Content-Type: application/json

{
    "content": "Parabéns John."
}

# =======================================
# USER ACTIONS (Beto)
# =======================================

### CREATE SOCIAL_POST
POST {{baseUrl}}/social-posts/
Authorization: {{tokenBeto}}
Content-Type: application/json

{
    "title": "Meu Primeiro Post",
    "content": "Este é o conteúdo do post."
}

### GET SOCIAL_POST
GET {{baseUrl}}/social-posts/1/
Authorization: {{tokenBeto}}
Content-Type: application/json

### GET ALL SOCIAL_POST
GET {{baseUrl}}/social-posts/
Authorization: {{tokenBeto}}
Content-Type: application/json

### EDIT SOCIAL_POST
PATCH {{baseUrl}}/social-posts/1/
Authorization: {{tokenBeto}}
Content-Type: application/json

{
    "title": "Título Atualizado teste",
    "content": "Conteúdo atualizado do post."
}

### DELETE SOCIAL_POST
DELETE {{baseUrl}}/social-posts/1/
Authorization: {{tokenBeto}}

### COMMENT SOCIAL_POST
POST {{baseUrl}}/social-posts/1/comment/
Authorization: {{tokenBeto}}
Content-Type: application/json

{
    "content": "Parabéns John."
}

# =======================================
